# Generated by Django 3.0.8 on 2023-10-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('profile', models.CharField(choices=[('ST', 'Student'), ('FA', 'Faculty'), ('OT', 'Other'), ('SF', 'Staff'), ('VI', 'Visitor')], default='ST', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
