# Generated by Django 3.2.22 on 2023-10-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20231016_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='lostdeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=100)),
                ('assemblyNumber', models.IntegerField(max_length=100)),
                ('year', models.IntegerField()),
                ('total_Candidates', models.IntegerField()),
                ('deposit_Lost', models.IntegerField()),
            ],
        ),
    ]
